USB_VID = 0x1209
USB_PID = 0x88ea
USB_PRODUCT = "Empyrean Alpha"
USB_MANUFACTURER = "Etherkit"

CHIP_VARIANT = SAMD21G18A
CHIP_FAMILY = samd21

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE
CIRCUITPY_SMALL_BUILD = 1

SUPEROPT_GC = 0
